# Generated by Django 4.2.30 on 2026-09-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'درانتظار پرداخت'), (2, ' موفقیت آمیز'), (3, 'لغو شده')], default=1),
        ),
    ]
