# Generated by Django 4.2.30 on 2026-09-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_avg_rate'),
        ('order', '0006_alter_ordermodel_options_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.productmodel'),
        ),
    ]
